language: php

php:
    - 5.5
    - 5.6
    - 7.0

env:
    - SILEX_VERSION=2.0.*

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer require silex/silex:${SILEX_VERSION}
    - composer require symfony/config:*
    - composer require symfony/routing:*
    - composer require mikey179/vfsStream:*

script: phpunit --coverage-text

sudo: false